imports:
    - { resource: test_common.yaml }

parameters:
    integration_http_log_path: '%env(HTTP_LOG_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\Integration\HttpLoggerFactory:

    app.tests.services.integration.httplogger:
        class: Psr\Log\LoggerInterface
        factory: [ '@App\Tests\Services\Integration\HttpLoggerFactory', 'create' ]
        arguments:
            $path: '%kernel.project_dir%/%integration_http_log_path%'

    webignition\HttpHistoryContainer\LoggableContainer:
        arguments:
            $logger: '@app.tests.services.integration.httplogger'

    app.tests.services.guzzle.handler:
        class: TijmenWierenga\Guzzle\Mocking\MockHandler
        factory: [ '@App\Tests\Services\Guzzle\HandlerFactory', 'createAlwaysOkMockHandler' ]

    App\Tests\Services\Guzzle\Middleware\Factory\HistoryMiddlewareFactory:

    GuzzleHttp\HandlerStack:
        factory: [ '@App\Tests\Services\Guzzle\HandlerStackFactory', 'create' ]
        arguments:
            $handler: '@app.tests.services.guzzle.handler'
            $middlewareFactories:
                - '@App\Tests\Services\Guzzle\Middleware\Factory\HistoryMiddlewareFactory'
                -