parameters:
    basil_local_fixtures_path: '%env(BASIL_LOCAL_FIXTURES_PATH)%'
    basil_local_source_path: '%env(BASIL_LOCAL_SOURCE_PATH)%'
    basil_local_upload_path: '%env(BASIL_LOCAL_UPLOAD_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\TestTestFactory:
        public: true

    App\Tests\Services\TestCallbackFactory:
        public: true

    App\Tests\Services\EnvironmentFactory:
        public: true

    App\Tests\Services\BasilFixtureHandler:
        public: true
        arguments:
            $fixturesPath: '%kernel.project_dir%/%basil_local_fixtures_path%'
            $uploadPath: '%kernel.project_dir%/%basil_local_upload_path%'
            $localSourcePath: '%kernel.project_dir%/%basil_local_source_path%'
