framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'App\Messenger\JsonMessageSerializer'

        routing:
            '*': async
