version: "3"

services:
  compiler:
    image: smartassert/basil-compiler:0.27
    volumes:
      - ${LOCAL_SOURCE_PATH}:${SOURCE_PATH}
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}

  chrome-runner:
    image: smartassert/chrome-runner:0.16
    volumes:
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}

  firefox-runner:
    image: smartassert/firefox-runner:0.16
    volumes:
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}

  delegator:
    image: smartassert/basil-runner-delegator:0.5
    environment:
      CHROME_RUNNER_HOST: chrome-runner
      CHROME_RUNNER_PORT: 8000
      FIREFOX_RUNNER_HOST: firefox-runner
      FIREFOX_RUNNER_PORT: 8000
    depends_on:
      - chrome-runner
      - firefox-runner

  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - app-web:app-web

  app-handler:
    image: smartassert/basil-worker-handler:0.4
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/worker-db?serverVersion=12&charset=utf8
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages
    depends_on:
      - compiler
      - delegator
      - postgres
      - rabbitmq

  app-web:
    image: smartassert/basil-worker-web:0.2
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/worker-db?serverVersion=12&charset=utf8
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages
    depends_on:
      - postgres
      - rabbitmq
