version: "3"

networks:
  primary:
    name: worker-network

services:
  compiler:
    image: smartassert/basil-compiler:0.27
    container_name: compiler
    networks:
      - primary
    volumes:
      - ${LOCAL_SOURCE_PATH}:${SOURCE_PATH}
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}

  chrome-runner:
    image: smartassert/chrome-runner:0.16
    container_name: chrome-runner
    networks:
      - primary
    volumes:
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}

  firefox-runner:
    image: smartassert/firefox-runner:0.16
    container_name: firefox-runner
    networks:
      - primary
    volumes:
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}

  delegator:
    image: smartassert/basil-runner-delegator:0.5
    container_name: delegator
    networks:
      - primary
    environment:
      CHROME_RUNNER_HOST: chrome-runner
      CHROME_RUNNER_PORT: 8000
      FIREFOX_RUNNER_HOST: firefox-runner
      FIREFOX_RUNNER_PORT: 8000
    depends_on:
      - chrome-runner
      - firefox-runner

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    networks:
      - primary
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  postgres:
    image: postgres:12.5
    container_name: postgres
    networks:
      - primary
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - primary
    ports:
      - 80:80
    links:
      - app-web:app-web
    volumes:
      - /var/log/nginx:/var/log/nginx

  app-handler:
    image: smartassert/basil-worker-handler:0.4
    container_name: app-handler
    networks:
      - primary
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/worker-db?serverVersion=12&charset=utf8
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages
    depends_on:
      - compiler
      - delegator
      - postgres
      - rabbitmq
    volumes:
      - /var/log/app-handler:/app/var/log

  app-web:
    image: smartassert/basil-worker-web:0.2
    container_name: app-web
    networks:
      - primary
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/worker-db?serverVersion=12&charset=utf8
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - /var/log/app-web:/app/var/log
