version: "3"

networks:
  primary:
    name: worker-network

services:
  compiler:
    image: ghcr.io/smartassert/compiler:0.29
    container_name: compiler
    networks:
      - primary
    volumes:
      - ${LOCAL_SOURCE_PATH}:${SOURCE_PATH}
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}

  chrome-runner:
    image: ghcr.io/smartassert/chrome-runner:0.18
    container_name: chrome-runner
    networks:
      - primary
    volumes:
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}

  firefox-runner:
    image: ghcr.io/smartassert/firefox-runner:0.18
    container_name: firefox-runner
    networks:
      - primary
    volumes:
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}

  delegator:
    image: ghcr.io/smartassert/runner-delegator:0.6
    container_name: delegator
    networks:
      - primary
    environment:
      CHROME_RUNNER_HOST: chrome-runner
      CHROME_RUNNER_PORT: 8000
      FIREFOX_RUNNER_HOST: firefox-runner
      FIREFOX_RUNNER_PORT: 8000
    depends_on:
      - chrome-runner
      - firefox-runner

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    networks:
      - primary
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  postgres:
    image: postgres:12.5
    container_name: postgres
    networks:
      - primary
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - primary
    ports:
      - ${NGINX_EXPOSED_PORT}:80
    links:
      - app-web:app-web
    volumes:
      - /var/log/nginx:/var/log/nginx

  app-web:
    build:
      context: $APP_BUILD_CONTEXT
      args:
        DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/worker-db?serverVersion=12&charset=utf8
        MESSENGER_TRANSPORT_DSN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/%2f/messages
    container_name: app-web
    networks:
      - primary
    depends_on:
      - compiler
      - delegator
      - postgres
      - rabbitmq
    volumes:
      - /var/log/app-web:/app/var/log
      - ${LOCAL_SOURCE_PATH}:${SOURCE_PATH}
      - ${LOCAL_TARGET_PATH}:${TARGET_PATH}
