version: "3"

services:
  http-fixtures:
    image: nginx:1.19
    container_name: http-fixtures
    networks:
      - primary
    volumes:
      - ./self-test/fixtures/http:/usr/share/nginx/html

  callback-receiver:
    image: mendhak/http-https-echo:19
    container_name: callback-receiver
    networks:
      - primary
