services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\JobStore:
        public: true

    App\Services\TestConfigurationStore:
        public: true

    App\Services\TestStore:
        public: true

    App\Services\Compiler:
        public: true
        arguments:
            $client: '@app.services.compiler-client'
            $compilerSourceDirectory: '%env(COMPILER_SOURCE_DIRECTORY)%'
            $compilerTargetDirectory: '%env(COMPILER_TARGET_DIRECTORY)%'

    App\Tests\Services\BasilFixtureHandler:
        public: true
        arguments:
            $fixturesPath: '%kernel.project_dir%/tests/Fixtures/basil'
            $uploadedPath: '%kernel.project_dir%/tests/Fixtures/Uploaded'

    App\Tests\Services\SourceStoreInitializer:
        public: true
