services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\SourceFileStore:
        public: true
        arguments:
            $path: '%kernel.project_dir%/var/basil'

    App\Services\SourceFactory:
        public: true

    App\Services\TestSerializer:
        public: true
        arguments:
            $compilerSourcePathPrefixRemover: '@app.services.path-prefix-remover.compiler-source'
            $compilerTargetPathPrefixRemover: '@app.services.path-prefix-remover.compiler-target'

    App\Tests\Services\SourceFileStoreInitializer:
        public: true

    App\Tests\Services\UploadedFileFactory:
        public: true

    App\Tests\Services\BasilFixtureHandler:
        public: true
        arguments:
            $fixturesPath: '%kernel.project_dir%/tests/Fixtures/Basil'
            $uploadedPath: '%kernel.project_dir%/tests/Fixtures/Uploaded'

    App\Tests\Services\TestTestFactory:
        public: true