imports:
    - { resource: services/test_common.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\TestTestMutator:
        public: true

    App\Tests\Services\Asserter\MessengerAsserter:
        public: true
        arguments:
            $transport: '@messenger.transport.async'

    App\Tests\Services\Asserter\SourceEntityAsserter:
        public: true

    App\Tests\Services\CallbackHttpErrorEventSubscriber:
        public: true

    App\Tests\Services\Asserter\TestEntityAsserter:
        public: true

    App\Tests\Services\EventListenerRemover:
        public: true
        arguments:
            $container: '@test.service_container'

    app.tests.services.guzzle.handler.queuing:
        public: true
        class: GuzzleHttp\Handler\MockHandler
        factory: [ '@App\Tests\Services\Guzzle\HandlerFactory', 'createQueuingMockHandler' ]

    GuzzleHttp\HandlerStack:
        factory: [ '@App\Tests\Services\Guzzle\HandlerStackFactory', 'create' ]
        arguments:
            $handler: '@app.tests.services.guzzle.handler.queuing'

    App\Tests\Services\Guzzle\HandlerFactory: ~

    App\Tests\Services\Guzzle\HandlerStackFactory: ~

    App\Tests\Services\Guzzle\ClientFactory: ~

    Psr\Http\Client\ClientInterface:
        class: GuzzleHttp\Client
        factory: [ '@App\Tests\Services\Guzzle\ClientFactory', 'get' ]

    App\Tests\Services\TestTestFactory:
        arguments:
            $compilerSourceDirectory: '%compiler_source_directory%'
