services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\BasilFixtureHandler:
        public: true
        arguments:
            $fixturesPath: '%kernel.project_dir%/tests/Fixtures/basil'
            $uploadedPath: '%kernel.project_dir%/tests/Fixtures/Uploaded'

    App\Tests\Services\SourceStoreInitializer:
        public: true

    App\Tests\Services\ClientRequestSender:
        public: true
        arguments:
            $client: '@test.client'

    App\Tests\Services\UploadedFileFactory:
        public: true
