imports:
    - { resource: services/test_common.yaml }
    - { resource: services/integration_common.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\SourceFactory:
        public: true

    webignition\SymfonyMessengerMessageDispatcher\Middleware\IgnoredMessageMiddleware:
        arguments:
            $messageClassNames:
                - App\Message\TimeoutCheckMessage

    webignition\SymfonyMessengerMessageDispatcher\MessageDispatcher:
        arguments:
            $middleware:
                - '@webignition\SymfonyMessengerMessageDispatcher\Middleware\IgnoredMessageMiddleware'
                - '@webignition\SymfonyMessengerMessageDispatcher\Middleware\DelayedMessage\DelayedMessageMiddleware'
                - '@webignition\SymfonyMessengerMessageDispatcher\Middleware\RetryByLimitMiddleware'
