imports:
    - { resource: services/integration.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\Integration\HttpLogReader:
        public: true
        arguments:
            $path: '%kernel.project_dir%/%integration_http_log_path%'

    App\Tests\Services\TestTestRepository:
        public: true
