parameters:
    basil_local_fixtures_path: '%env(BASIL_LOCAL_FIXTURES_PATH)%'
    basil_local_source_path: '%env(BASIL_LOCAL_SOURCE_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\CallbackSender:
        public: true

    App\Services\SourceFileStore:
        public: true
        arguments:
            $path: '%kernel.project_dir%/%compiler_source_directory%'

    App\Services\SourceFactory:
        public: true

    App\Services\TestStateMutator:
        public: true

    App\Services\TestSerializer:
        public: true
        arguments:
            $compilerSourcePathPrefixRemover: '@app.services.path-prefix-remover.compiler-source'
            $compilerTargetPathPrefixRemover: '@app.services.path-prefix-remover.compiler-target'

    App\Services\Compiler:
        public: true
        arguments:
            $client: '@app.services.compiler-client'
            $compilerSourceDirectory: '%kernel.project_dir%/%compiler_source_directory%'
            $compilerTargetDirectory: '%kernel.project_dir%/%compiler_target_directory%'

    App\Services\CallbackResponseHandler:
        public: true

    App\Services\EventCallbackFactory\CompilationFailedEventCallbackFactory:
        public: true

    App\Services\EventCallbackFactory\CompilationPassedEventCallbackFactory:
        public: true

    App\Services\EventCallbackFactory\CompilationStartedEventCallbackFactory:
        public: true

    App\Services\EventCallbackFactory\JobTimeoutEventCallbackFactory:
        public: true

    App\Services\EventCallbackFactory\NoPayloadEventCallbackFactory:
        public: true

    App\Services\EventCallbackFactory\TestEventCallbackFactory:
        public: true

    App\Services\CallbackFactory:
        public: true
        arguments:
            $eventCallbackFactories:
                - '@App\Services\EventCallbackFactory\CompilationStartedEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\CompilationPassedEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\CompilationFailedEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\TestEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\JobTimeoutEventCallbackFactory'
                - '@App\Services\EventCallbackFactory\NoPayloadEventCallbackFactory'

    App\Services\TestFactory:
        public: true

    App\Services\ApplicationWorkflowHandler:
        public: true

    App\Services\TestCanceller:
        public: true

    App\Services\CompilationWorkflowHandler:
        public: true

    App\Services\ExecutionWorkflowHandler:
        public: true

    App\Services\TestExecutor:
        public: true
        arguments:
            $delegatorClient: '@app.services.delegator-client'

    App\MessageDispatcher\TimeoutCheckMessageDispatcher:
        public: true

    App\Tests\Services\SourceFileStoreInitializer:
        public: true
        arguments:
            $path: '%kernel.project_dir%/%compiler_source_directory%'

    App\Tests\Services\UploadedFileFactory:
        public: true

    App\Tests\Services\BasilFixtureHandler:
        public: true
        arguments:
            $fixturesPath: '%kernel.project_dir%/%basil_local_fixtures_path%'
            $uploadedPath: '%kernel.project_dir%/%basil_local_source_path%'

    App\Tests\Services\TestTestFactory:
        public: true

    App\Tests\Services\TestTestMutator:
        public: true

    App\Tests\Services\EnvironmentFactory:
        public: true

    App\Tests\Services\ClientRequestSender:
        public: true
        arguments:
            $client: '@test.client'

    App\Tests\Services\Asserter\MessengerAsserter:
        public: true
        arguments:
            $transport: '@messenger.transport.async'

    App\Tests\Services\Asserter\SourceEntityAsserter:
        public: true

    App\Tests\Services\Asserter\JsonResponseAsserter:
        public: true

    App\Tests\Services\CallbackHttpErrorEventSubscriber:
        public: true

    App\Tests\Services\Asserter\TestEntityAsserter:
        public: true

    App\Tests\Services\EventListenerRemover:
        public: true
        arguments:
            $container: '@test.service_container'

    app.tests.services.guzzle.handler.queuing:
        public: true
        class: GuzzleHttp\Handler\MockHandler
        factory: [ '@App\Tests\Services\Guzzle\HandlerFactory', 'createQueuingMockHandler' ]

    GuzzleHttp\HandlerStack:
        factory: [ '@App\Tests\Services\Guzzle\HandlerStackFactory', 'create' ]
        arguments:
            $handler: '@app.tests.services.guzzle.handler.queuing'

    App\Tests\Services\Guzzle\HandlerFactory: ~

    App\Tests\Services\Guzzle\HandlerStackFactory: ~

    App\Tests\Services\Guzzle\ClientFactory: ~

    Psr\Http\Client\ClientInterface:
        class: GuzzleHttp\Client
        factory: [ '@App\Tests\Services\Guzzle\ClientFactory', 'get' ]
