parameters:
    basil_local_fixtures_path: '%env(BASIL_LOCAL_FIXTURES_PATH)%'
    basil_local_source_path: '%env(BASIL_LOCAL_SOURCE_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\SourceFileStore:
        public: true
        arguments:
            $path: '%kernel.project_dir%/%compiler_source_directory%'

    App\Services\SourceFactory:
        public: true

    App\Services\TestSerializer:
        public: true
        arguments:
            $compilerSourcePathPrefixRemover: '@app.services.path-prefix-remover.compiler-source'
            $compilerTargetPathPrefixRemover: '@app.services.path-prefix-remover.compiler-target'

    App\Services\Compiler:
        public: true
        arguments:
            $client: '@app.services.compiler-client'
            $compilerSourceDirectory: '%kernel.project_dir%/%compiler_source_directory%'
            $compilerTargetDirectory: '%kernel.project_dir%/%compiler_target_directory%'

    App\Services\CallbackResponseHandler:
        public: true

    App\Tests\Services\SourceFileStoreInitializer:
        public: true
        arguments:
            $path: '%kernel.project_dir%/%compiler_source_directory%'

    App\Tests\Services\UploadedFileFactory:
        public: true

    App\Tests\Services\BasilFixtureHandler:
        public: true
        arguments:
            $fixturesPath: '%kernel.project_dir%/%basil_local_fixtures_path%'
            $uploadedPath: '%kernel.project_dir%/%basil_local_source_path%'

    App\Tests\Services\TestTestFactory:
        public: true

    App\Tests\Services\EnvironmentFactory:
        public: true

    App\Tests\Services\ClientRequestSender:
        public: true
        arguments:
            $client: '@test.client'

    App\Tests\Services\Asserter\MessengerAsserter:
        public: true
        arguments:
            $transport: '@messenger.transport.async'

    App\Tests\Services\Asserter\SourceEntityAsserter:
        public: true

    App\Tests\Services\CallbackHttpErrorEventSubscriber:
        public: true
