services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\JobStore:
        public: true

    App\Services\TestConfigurationStore:
        public: true

    App\Services\TestStore:
        public: true

    App\Services\Compiler:
        public: true
        arguments:
            $client: '@app.services.compiler-client'
            $compilerSourceDirectory: '%env(COMPILER_SOURCE_DIRECTORY)%'
            $compilerTargetDirectory: '%env(COMPILER_TARGET_DIRECTORY)%'

    App\Services\CallbackSender:
        public: true
        arguments:
            $retryLimit: '%callback_retry_limit%'

    App\MessageHandler\CompileSourceHandler:
        public: true

    App\Services\JobSourceFinder:
        public: true

    App\Services\CompilationWorkflowHandler:
        public: true

    App\Services\TestExecutor:
        public: true
        arguments:
            $delegatorClient: '@app.services.delegator-client'

    App\MessageHandler\ExecuteTestHandler:
        public: true

    App\Services\ExecutionWorkflowHandler:
        public: true

    App\Services\CompilationWorkflowFactory:
        public: true

    App\Services\ExecutionWorkflowFactory:
        public: true

    App\Services\TestFactory:
        public: true

    App\Services\CallbackResponseHandler:
        public: true

    App\Services\SourceCompileEventDispatcher:
        public: true

    App\EventSubscriber\TestFailedEventSubscriber:
        public: true

    App\MessageDispatcher\SendCallbackMessageDispatcher:
        public: true

    App\Services\TestCanceller:
        public: true

    App\Tests\Services\BasilFixtureHandler:
        public: true
        arguments:
            $fixturesPath: '%kernel.project_dir%/tests/Fixtures/basil'
            $uploadedPath: '%kernel.project_dir%/tests/Fixtures/Uploaded'

    App\Tests\Services\SourceStoreInitializer:
        public: true

    App\Tests\Services\SourcesAddedEventSubscriber:
        public: true

    App\Tests\Services\CallbackHttpExceptionEventSubscriber:
        public: true

    App\Tests\Services\CallbackHttpResponseEventSubscriber:
        public: true

    App\Tests\Services\Guzzle\HandlerFactory: ~

    GuzzleHttp\Handler\MockHandler:
        class: GuzzleHttp\Handler\MockHandler
        factory: [ '@App\Tests\Services\Guzzle\HandlerFactory', 'createQueuingMockHandler' ]

    App\Tests\Services\Guzzle\HandlerStackFactory: ~

    GuzzleHttp\HandlerStack:
        factory: [ '@App\Tests\Services\Guzzle\HandlerStackFactory', 'create' ]
        arguments:
            $handler: '@GuzzleHttp\Handler\MockHandler'

    App\Tests\Services\Guzzle\ClientFactory: ~

    Psr\Http\Client\ClientInterface:
        class: GuzzleHttp\Client
        factory: [ '@App\Tests\Services\Guzzle\ClientFactory', 'get' ]

    App\Tests\Services\ClientRequestSender:
        public: true
        arguments:
            $client: '@test.client'

    App\Tests\Services\UploadedFileFactory:
        public: true

    App\Tests\Services\TestTestFactory:
        public: true

    App\Tests\Services\TestTestRepository:
        public: true
