services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\JobStore:
        public: true

    App\Services\TestConfigurationStore:
        public: true

    App\Tests\Services\BasilFixtureHandler:
        public: true
        arguments:
            $fixturesPath: '%kernel.project_dir%/tests/Fixtures/basil'
            $uploadedPath: '%kernel.project_dir%/tests/Fixtures/Uploaded'

    App\Tests\Services\SourceStoreInitializer:
        public: true
