name: Static

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ecs:
    name: Easy Coding Standard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Easy Coding Standard Action
        uses: zingimmick/ecs-action@0.0.6

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
          CHECK_PLATFORM_REQUIREMENTS: false
        with:
          args: analyse --no-progress
