name: Static

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ecs:
    name: Easy Coding Standard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: php-actions/composer@v2
        with:
          args: --ignore-platform-reqs --no-progress

      - name: Run ECS
        run: composer cs-ecs

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
          CHECK_PLATFORM_REQUIREMENTS: false
        with:
          args: analyse --no-progress
