name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: Unit tests - PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Download dependencies
        uses: php-actions/composer@v2
        with:
          args: --ignore-platform-reqs --quiet

      - name: Run PHPUnit unit tests
        run: composer test-unit

  functional:
    name: Functional tests - PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: amqp, pgsql

      - name: Download dependencies
        uses: php-actions/composer@v2
        with:
          args: --ignore-platform-reqs --quiet

      - name: Setup functional test environment
        run: composer functional-setup

      - name: Run tests
        run: composer test-functional
        env:
          DATABASE_URL: postgres://postgres:password!@127.0.0.1:5432/worker-db?charset=UTF-8

      - name: Teardown functional test environment
        run: |
          composer functional-teardown
          rm -Rf $PWD/var/basil/local/source/*

  integration:
    name: Integration tests - PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: amqp, pgsql

      - name: Download dependencies
        uses: php-actions/composer@v2
        with:
          args: --ignore-platform-reqs --quiet

      - name: Setup integration test environment
        run: |
          mkdir -p $PWD/var/basil/local/tests
          composer integration-setup
          composer integration-chown-app-source
          sudo chown -R www-data:www-data $PWD/var/basil/local

      - name: Run tests
        run: |
          composer test-integration-sync
          composer db-recreate
          php bin/console --env=integration_async messenger:consume async > /dev/null &
          composer test-integration-async
          php bin/console --env=integration_async messenger:stop
          composer db-recreate
          composer test-integration

      - name: Teardown integration test environment
        run: |
          sudo composer integration-teardown
          sudo rm -Rf $PWD/var/basil/local/tests/*
