name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: php-actions/composer@v2
        with:
          args: --ignore-platform-reqs --quiet

      - name: Run PHPUnit unit tests
        run: composer test-unit

  functional:
    name: Functional tests
    runs-on: ubuntu-latest

#    services:
#      postgres:
#        image: postgres:12.4
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: password!
#          POSTGRES_DB: basil_worker_db
#        ports:
#          - 5432/tcp

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: amqp, pgsql

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        user: actions/cache@v2
        with:
          paths: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: |
          composer install --no-progress --prefer-dist
#
#      - name: Run DB migrations
#        run: |
#          php bin/console doctrine:database:create --no-interaction
#          php bin/conosole doctrine:migrations:migrate --no-interaction
#
#      - name: Run tests
#        run: |
#          composer test-functional
